### ISSUE TITLE
Skrive hva denne kan brukes til i README

### ISSUE THREAD

**Issue by ahusby** [nais/login#8]
Jeg kom over dette repoet da jeg strevde med å få satt opp Trivy scan i en reusable workflow. Jeg så at et annet team hadde brukt denne. Foreslår at readme-filen får mer innhold om hva denne kan brukes til, use cases, eksempel på bruk i et use case. Hvis det er flere ting den er men å brukes til, da. Hvis ønskelig kan jeg lage en pull-request på readme-fila basert på det jeg har kjempet meg til nå i repoet navikt/toi-github-actions-workflows.

**Comment by Kyrremann** [comment]
Sikkert enklest at du prøver deg på først, så kan vi ev. fylle ut de tingene du ikke har svaret på.

**Comment by ahusby** [comment]
Hva med https://github.com/nais/login/pull/9 , @Kyrremann ?
